/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-17 09:35:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.inventory.util.DBConnection;

public final class viewProducts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.inventory.util.DBConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Inventory Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("margin:0;\r\n");
      out.write("font-family:Segoe UI;\r\n");
      out.write("background:#f1f3f6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar{\r\n");
      out.write("width:220px;\r\n");
      out.write("height:100vh;\r\n");
      out.write("background:#0f1c2e;\r\n");
      out.write("color:white;\r\n");
      out.write("position:fixed;\r\n");
      out.write("padding:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar h2{\r\n");
      out.write("margin-bottom:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a{\r\n");
      out.write("display:block;\r\n");
      out.write("color:white;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("margin:18px 0;\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover{\r\n");
      out.write("color:#00d9ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main{\r\n");
      out.write("margin-left:240px;\r\n");
      out.write("padding:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cards{\r\n");
      out.write("display:flex;\r\n");
      out.write("gap:25px;\r\n");
      out.write("margin-bottom:35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card{\r\n");
      out.write("background:white;\r\n");
      out.write("padding:25px;\r\n");
      out.write("border-radius:10px;\r\n");
      out.write("width:230px;\r\n");
      out.write("box-shadow:0 4px 10px rgba(0,0,0,0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card h3{\r\n");
      out.write("margin:0;\r\n");
      out.write("color:#555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card h2{\r\n");
      out.write("margin-top:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search{\r\n");
      out.write("margin-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search input{\r\n");
      out.write("padding:10px;\r\n");
      out.write("width:300px;\r\n");
      out.write("border-radius:6px;\r\n");
      out.write("border:1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("width:100%;\r\n");
      out.write("border-collapse:collapse;\r\n");
      out.write("background:white;\r\n");
      out.write("border-radius:8px;\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("box-shadow:0 2px 8px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th{\r\n");
      out.write("background:#0f1c2e;\r\n");
      out.write("color:white;\r\n");
      out.write("padding:14px;\r\n");
      out.write("text-align:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("padding:14px;\r\n");
      out.write("border-bottom:1px solid #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:hover{\r\n");
      out.write("background:#f7f9fc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lowstock{\r\n");
      out.write("color:red;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit{\r\n");
      out.write("color:#007bff;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete{\r\n");
      out.write("color:red;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function searchProduct(){\r\n");
      out.write("let input=document.getElementById(\"search\").value.toLowerCase();\r\n");
      out.write("let rows=document.querySelectorAll(\"tbody tr\");\r\n");
      out.write("\r\n");
      out.write("rows.forEach(row=>{\r\n");
      out.write("let text=row.innerText.toLowerCase();\r\n");
      out.write("row.style.display=text.includes(input) ? \"\" : \"none\";\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("<h2>Dom Cricket Store</h2>\r\n");
      out.write("\r\n");
      out.write("<a href=\"ViewProductsServlet\">Dashboard</a>\r\n");
      out.write("<a href=\"addProduct.jsp\">Add Product</a>\r\n");
      out.write("<a href=\"#\">Logout</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("<h1>Dashboard Overview</h1>\r\n");
      out.write("\r\n");
      out.write("<div class=\"cards\">\r\n");
      out.write("\r\n");


Connection conn=DBConnection.getConnection();

Statement s1=conn.createStatement();
ResultSet r1=s1.executeQuery("SELECT COUNT(*) FROM products");
r1.next();

Statement s2=conn.createStatement();
ResultSet r2=s2.executeQuery("SELECT SUM(quantity) FROM products");
r2.next();

Statement s3=conn.createStatement();
ResultSet r3=s3.executeQuery("SELECT SUM(price*quantity) FROM products");
r3.next();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("<h3>Total Products</h3>\r\n");
      out.write("<h2>");
      out.print(r1.getInt(1));
      out.write("</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("<h3>Total Stock</h3>\r\n");
      out.write("<h2>");
      out.print(r2.getInt(1));
      out.write("</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("<h3>Total Inventory Value</h3>\r\n");
      out.write("<h2>");
      out.print(r3.getDouble(1));
      out.write(" Rs</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>Product List</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"search\">\r\n");
      out.write("<input type=\"text\" id=\"search\" onkeyup=\"searchProduct()\" placeholder=\"Search product...\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>ID</th>\r\n");
      out.write("<th>Name</th>\r\n");
      out.write("<th>Price</th>\r\n");
      out.write("<th>Quantity</th>\r\n");
      out.write("<th>Edit</th>\r\n");
      out.write("<th>Delete</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("\r\n");
      out.write("<tbody>\r\n");
      out.write("\r\n");


Statement stmt=conn.createStatement();
ResultSet rs=stmt.executeQuery("SELECT * FROM products");

while(rs.next()){

int id=rs.getInt("id");
String name=rs.getString("name");
double price=rs.getDouble("price");
int qty=rs.getInt("quantity");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td>");
      out.print(id);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(name);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(price);
      out.write(" Rs</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");

if(qty<5){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"lowstock\">Only ");
      out.print(qty);
      out.write(" left</span>\r\n");
      out.write("\r\n");

}else{

      out.write("\r\n");
      out.write("\r\n");
      out.print(qty);
      out.write("\r\n");
      out.write("\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("<a class=\"edit\" href=\"EditProductServlet?id=");
      out.print(id);
      out.write("\">Edit</a>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("<a class=\"delete\" href=\"DeleteProductServlet?id=");
      out.print(id);
      out.write("\">Delete</a>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
